server:
  port: 8084
  servlet:
    context-path: /qualificationSystem
spring:
  application:
    name: qualificationSystem
  jackson.serialization.indent-output: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: asd
    password: asd
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
  h2.console:
    enabled: true
    path: /db