server:
  port: 8084
  servlet:
    context-path: /qualificationSystem
spring:
  application:
    name: qualificationSystem
  jackson.serialization.indent-output: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:qualificationdb}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
